/**
 * Crop parameter library for 21 major Indian field crops.
 *
 * Sources
 * - Kc, stage lengths, rooting depth, p: FAO-56 (Allen et al., 1998), Tables 11, 12, 22.
 * - Ky: FAO-33 (Doorenbos & Kassam, 1979); estimated from agronomic analogues where absent.
 * - Cardinal temperatures and stress thresholds: ICAR crop production guides.
 * - Prices: MSP for Kharif Marketing Season 2026-27 (CCEA, 13 May 2026) and Rabi Marketing
 *   Season 2027-28 (CCEA, 30 Sep 2026). Vegetables have no MSP; an indicative mandi modal
 *   price is used and flagged as such.
 * - Cost of cultivation: indicative A2+FL per acre consistent with CACP cost estimates.
 *
 * These parameters form the shared "national model" that states can calibrate and
 * publish through the model registry (see `domain/crops/registry.ts`).
 */
import type { CropModel, PestRisk, SowingWindow } from "./types";

const KMS_2026 = "MSP KMS 2026-27";
const RMS_2027 = "MSP RMS 2027-28";
const MANDI = "Indicative mandi modal price";

const w = (
  season: SowingWindow["season"],
  fromMonth: number,
  fromDay: number,
  toMonth: number,
  toDay: number,
): SowingWindow => ({
  season,
  from: { month: fromMonth, day: fromDay },
  to: { month: toMonth, day: toDay },
});

const CEREAL_STAGES: [string, string, string, string] = [
  "Germination & establishment",
  "Tillering & vegetative growth",
  "Flowering & grain filling",
  "Ripening",
];
const CEREAL_NOTES: [string, string, string, string] = [
  "Seed germinates and roots establish; keep the seedbed moist.",
  "Leaves and tillers multiply; the crop's nitrogen demand peaks.",
  "Most sensitive stage: water or heat stress now cuts grain number and weight.",
  "Grain dries down; irrigation can stop and the crop is readied for harvest.",
];
const PULSE_STAGES: [string, string, string, string] = [
  "Germination & nodulation",
  "Branching & vegetative growth",
  "Flowering & pod filling",
  "Pod maturity",
];
const PULSE_NOTES: [string, string, string, string] = [
  "Root nodules form and begin fixing nitrogen from the air.",
  "Branches spread; avoid waterlogging, which kills nodules.",
  "Flowers and pods set; one protective irrigation here pays the most.",
  "Pods turn brown and dry; harvest before they shatter.",
];
const OILSEED_STAGES: [string, string, string, string] = [
  "Germination & rosette",
  "Branching",
  "Flowering & seed filling",
  "Maturity",
];
const OILSEED_NOTES: [string, string, string, string] = [
  "Seedlings emerge; thin to the right spacing.",
  "Primary and secondary branches form the crop's yield frame.",
  "Flowers open and seeds fill with oil; protect from stress and pests.",
  "Seeds harden and oil content peaks; harvest on time.",
];
const VEG_STAGES: [string, string, string, string] = [
  "Establishment",
  "Vegetative growth",
  "Flowering & fruit/bulb set",
  "Harvest period",
];
const VEG_NOTES: [string, string, string, string] = [
  "Transplants or sprouts establish; frequent light irrigation.",
  "Canopy expands quickly; feed and protect foliage.",
  "Yield forms now; steady moisture prevents cracking and drop.",
  "Produce matures and is harvested; reduce irrigation towards the end.",
];

const risk = (
  name: string,
  kind: PestRisk["kind"],
  rule: PestRisk["rule"],
  stages: PestRisk["stages"],
  action: string,
): PestRisk => ({ name, kind, rule, stages, action });

export const CROPS: readonly CropModel[] = [
  {
    id: "rice",
    name: "Rice (Paddy)",
    localName: "Dhan",
    category: "cereal",
    sowingWindows: [w("kharif", 6, 1, 7, 31)],
    durationDays: 125,
    stageFractions: [0.2, 0.2, 0.4, 0.2],
    stageLabels: ["Nursery & transplanting", "Tillering", "Panicle initiation & flowering", "Grain ripening"],
    stageNotes: [
      "Seedlings establish after transplanting; keep 2-3 cm standing water.",
      "Tillers multiply; apply the second nitrogen split.",
      "Panicles emerge and flower; the crop must not dry out now.",
      "Grains fill and harden; drain the field 10 days before harvest.",
    ],
    temperature: { base: 10, optLow: 25, optHigh: 32, max: 40 },
    heatStressC: 35,
    coldStressC: 15,
    kc: { ini: 1.05, mid: 1.2, end: 0.9 },
    rootDepthM: 0.5,
    depletionFraction: 0.2,
    ky: 1.3,
    maxHeightCm: 100,
    harvestIndex: 0.45,
    potentialYieldKgHa: 6000,
    price: { perQuintalInr: 2441, basis: KMS_2026 },
    priceVolatility: 0.08,
    costPerAcreInr: 26000,
    byproductPerAcreInr: 2000,
    phRange: [5.0, 8.0],
    salinityToleranceEc: 1.5,
    nitrogenFixing: false,
    waterIntensity: "high",
    residueBurningRisk: true,
    risks: [
      risk("Rice blast", "disease", "warm_humid", ["development", "mid"], "Spray tricyclazole 75 WP @ 0.6 g/L at first spindle-shaped leaf spots; avoid excess nitrogen."),
      risk("Brown plant hopper", "pest", "warm_humid", ["mid"], "Drain water for 3-4 days and check the base of hills; spray only above 10 hoppers per hill."),
    ],
  },
  {
    id: "wheat",
    name: "Wheat",
    localName: "Gehun",
    category: "cereal",
    sowingWindows: [w("rabi", 10, 25, 12, 20)],
    durationDays: 135,
    stageFractions: [0.15, 0.22, 0.41, 0.22],
    stageLabels: ["Germination & crown root", "Tillering & jointing", "Heading & grain filling", "Ripening"],
    stageNotes: [
      "Seedlings emerge; the first irrigation at crown-root initiation (~21 days) is critical.",
      "Tillers form and the stem elongates; top-dress nitrogen with irrigation.",
      "Ears emerge and grains fill; heat above 32 °C now shrivels the grain.",
      "Grain hardens; stop irrigation and harvest when golden.",
    ],
    temperature: { base: 3, optLow: 15, optHigh: 23, max: 34 },
    heatStressC: 32,
    coldStressC: 1,
    kc: { ini: 0.4, mid: 1.15, end: 0.3 },
    rootDepthM: 1.5,
    depletionFraction: 0.55,
    ky: 1.05,
    maxHeightCm: 95,
    harvestIndex: 0.42,
    potentialYieldKgHa: 5000,
    price: { perQuintalInr: 2610, basis: RMS_2027 },
    priceVolatility: 0.08,
    costPerAcreInr: 20000,
    byproductPerAcreInr: 7000,
    phRange: [6.0, 8.5],
    salinityToleranceEc: 3.0,
    nitrogenFixing: false,
    waterIntensity: "medium",
    residueBurningRisk: true,
    risks: [
      risk("Yellow rust", "disease", "cool_humid", ["development", "mid"], "Scout for yellow stripes on leaves; spray propiconazole 25 EC @ 1 ml/L at first sign."),
      risk("Wheat aphid", "pest", "cool_dry", ["mid"], "Spray only above 10 aphids per tiller; conserve ladybird beetles."),
    ],
  },
  {
    id: "maize",
    name: "Maize",
    localName: "Makka",
    category: "cereal",
    sowingWindows: [w("kharif", 6, 1, 7, 31), w("rabi", 10, 1, 11, 30)],
    durationDays: 105,
    stageFractions: [0.18, 0.3, 0.3, 0.22],
    stageLabels: ["Emergence", "Knee-high to tasseling", "Silking & grain filling", "Dent & maturity"],
    stageNotes: CEREAL_NOTES,
    temperature: { base: 10, optLow: 24, optHigh: 32, max: 40 },
    heatStressC: 36,
    coldStressC: 8,
    kc: { ini: 0.3, mid: 1.2, end: 0.35 },
    rootDepthM: 1.2,
    depletionFraction: 0.55,
    ky: 1.25,
    maxHeightCm: 220,
    harvestIndex: 0.45,
    potentialYieldKgHa: 6000,
    price: { perQuintalInr: 2410, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 17000,
    byproductPerAcreInr: 2000,
    phRange: [5.5, 8.0],
    salinityToleranceEc: 1.7,
    nitrogenFixing: false,
    waterIntensity: "medium",
    residueBurningRisk: false,
    risks: [
      risk("Fall armyworm", "pest", "warm_humid", ["initial", "development"], "Check whorls for fresh frass; apply sand + lime in whorls or spray emamectin benzoate 5 SG @ 0.4 g/L."),
      risk("Turcicum leaf blight", "disease", "cool_humid", ["development", "mid"], "Spray mancozeb 75 WP @ 2.5 g/L when long grey lesions appear."),
    ],
  },
  {
    id: "bajra",
    name: "Pearl millet",
    localName: "Bajra",
    category: "millet",
    sowingWindows: [w("kharif", 6, 15, 7, 31)],
    durationDays: 85,
    stageFractions: [0.14, 0.24, 0.38, 0.24],
    stageLabels: CEREAL_STAGES,
    stageNotes: CEREAL_NOTES,
    temperature: { base: 12, optLow: 28, optHigh: 35, max: 44 },
    heatStressC: 42,
    coldStressC: 10,
    kc: { ini: 0.3, mid: 1.0, end: 0.3 },
    rootDepthM: 1.5,
    depletionFraction: 0.55,
    ky: 0.85,
    maxHeightCm: 200,
    harvestIndex: 0.3,
    potentialYieldKgHa: 3000,
    price: { perQuintalInr: 2900, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 9500,
    byproductPerAcreInr: 4000,
    phRange: [5.5, 8.5],
    salinityToleranceEc: 4.0,
    nitrogenFixing: false,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Downy mildew (green ear)", "disease", "warm_humid", ["initial", "development"], "Use metalaxyl-treated seed and rogue out infected plants early."),
    ],
  },
  {
    id: "jowar",
    name: "Sorghum",
    localName: "Jowar",
    category: "millet",
    sowingWindows: [w("kharif", 6, 15, 7, 31), w("rabi", 9, 15, 10, 31)],
    durationDays: 110,
    stageFractions: [0.16, 0.28, 0.32, 0.24],
    stageLabels: CEREAL_STAGES,
    stageNotes: CEREAL_NOTES,
    temperature: { base: 10, optLow: 26, optHigh: 34, max: 42 },
    heatStressC: 40,
    coldStressC: 8,
    kc: { ini: 0.3, mid: 1.0, end: 0.55 },
    rootDepthM: 1.5,
    depletionFraction: 0.55,
    ky: 0.9,
    maxHeightCm: 220,
    harvestIndex: 0.35,
    potentialYieldKgHa: 3500,
    price: { perQuintalInr: 4023, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 12500,
    byproductPerAcreInr: 4500,
    phRange: [5.5, 8.5],
    salinityToleranceEc: 3.4,
    nitrogenFixing: false,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Shoot fly", "pest", "warm_humid", ["initial"], "Sow early and use a higher seed rate; spray only if dead-hearts exceed 10%."),
    ],
  },
  {
    id: "ragi",
    name: "Finger millet",
    localName: "Ragi",
    category: "millet",
    sowingWindows: [w("kharif", 6, 1, 8, 15)],
    durationDays: 110,
    stageFractions: [0.14, 0.24, 0.38, 0.24],
    stageLabels: CEREAL_STAGES,
    stageNotes: CEREAL_NOTES,
    temperature: { base: 10, optLow: 24, optHigh: 32, max: 40 },
    heatStressC: 38,
    coldStressC: 10,
    kc: { ini: 0.3, mid: 1.0, end: 0.3 },
    rootDepthM: 1.0,
    depletionFraction: 0.55,
    ky: 0.9,
    maxHeightCm: 100,
    harvestIndex: 0.35,
    potentialYieldKgHa: 3000,
    price: { perQuintalInr: 5205, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 13000,
    byproductPerAcreInr: 3500,
    phRange: [5.0, 8.2],
    salinityToleranceEc: 3.0,
    nitrogenFixing: false,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Finger millet blast", "disease", "warm_humid", ["development", "mid"], "Spray carbendazim 50 WP @ 1 g/L at neck and finger infection."),
    ],
  },
  {
    id: "chickpea",
    name: "Chickpea",
    localName: "Chana",
    category: "pulse",
    sowingWindows: [w("rabi", 10, 1, 11, 30)],
    durationDays: 115,
    stageFractions: [0.17, 0.26, 0.33, 0.24],
    stageLabels: PULSE_STAGES,
    stageNotes: PULSE_NOTES,
    temperature: { base: 5, optLow: 15, optHigh: 25, max: 35 },
    heatStressC: 32,
    coldStressC: 2,
    kc: { ini: 0.4, mid: 1.0, end: 0.35 },
    rootDepthM: 0.8,
    depletionFraction: 0.5,
    ky: 0.85,
    maxHeightCm: 50,
    harvestIndex: 0.4,
    potentialYieldKgHa: 2000,
    price: { perQuintalInr: 5958, basis: RMS_2027 },
    priceVolatility: 0.15,
    costPerAcreInr: 13500,
    byproductPerAcreInr: 1500,
    phRange: [6.0, 8.5],
    salinityToleranceEc: 1.5,
    nitrogenFixing: true,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Gram pod borer", "pest", "warm_flowering", ["mid"], "Install 5 pheromone traps per acre and bird perches; spray NSKE 5% at 1 larva per plant."),
      risk("Ascochyta blight", "disease", "cool_humid", ["development", "mid"], "Spray mancozeb 75 WP @ 2 g/L on first lesions; avoid irrigation in cloudy weather."),
    ],
  },
  {
    id: "lentil",
    name: "Lentil",
    localName: "Masoor",
    category: "pulse",
    sowingWindows: [w("rabi", 10, 15, 11, 30)],
    durationDays: 115,
    stageFractions: [0.13, 0.2, 0.4, 0.27],
    stageLabels: PULSE_STAGES,
    stageNotes: PULSE_NOTES,
    temperature: { base: 4, optLow: 15, optHigh: 24, max: 32 },
    heatStressC: 32,
    coldStressC: 0,
    kc: { ini: 0.4, mid: 1.1, end: 0.3 },
    rootDepthM: 0.7,
    depletionFraction: 0.5,
    ky: 0.9,
    maxHeightCm: 40,
    harvestIndex: 0.35,
    potentialYieldKgHa: 1600,
    price: { perQuintalInr: 7390, basis: RMS_2027 },
    priceVolatility: 0.15,
    costPerAcreInr: 11500,
    byproductPerAcreInr: 1500,
    phRange: [6.0, 8.0],
    salinityToleranceEc: 1.3,
    nitrogenFixing: true,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Lentil rust", "disease", "cool_humid", ["mid"], "Spray mancozeb 75 WP @ 2 g/L at first pustules."),
    ],
  },
  {
    id: "pigeonpea",
    name: "Pigeon pea",
    localName: "Arhar / Tur",
    category: "pulse",
    sowingWindows: [w("kharif", 6, 1, 7, 31)],
    durationDays: 165,
    stageFractions: [0.12, 0.28, 0.36, 0.24],
    stageLabels: PULSE_STAGES,
    stageNotes: PULSE_NOTES,
    temperature: { base: 10, optLow: 25, optHigh: 33, max: 40 },
    heatStressC: 38,
    coldStressC: 4,
    kc: { ini: 0.4, mid: 1.15, end: 0.35 },
    rootDepthM: 1.5,
    depletionFraction: 0.55,
    ky: 0.85,
    maxHeightCm: 200,
    harvestIndex: 0.3,
    potentialYieldKgHa: 2000,
    price: { perQuintalInr: 8450, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 15000,
    byproductPerAcreInr: 2500,
    phRange: [5.5, 8.0],
    salinityToleranceEc: 1.5,
    nitrogenFixing: true,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Pod borer complex", "pest", "warm_flowering", ["mid"], "Use pheromone traps and shake plants over a sheet; spray chlorantraniliprole 18.5 SC @ 0.3 ml/L if needed."),
    ],
  },
  {
    id: "moong",
    name: "Green gram",
    localName: "Moong",
    category: "pulse",
    sowingWindows: [w("kharif", 6, 15, 7, 31), w("zaid", 3, 1, 4, 15)],
    durationDays: 70,
    stageFractions: [0.18, 0.27, 0.36, 0.19],
    stageLabels: PULSE_STAGES,
    stageNotes: PULSE_NOTES,
    temperature: { base: 12, optLow: 27, optHigh: 35, max: 42 },
    heatStressC: 40,
    coldStressC: 12,
    kc: { ini: 0.4, mid: 1.05, end: 0.35 },
    rootDepthM: 0.7,
    depletionFraction: 0.45,
    ky: 1.0,
    maxHeightCm: 55,
    harvestIndex: 0.3,
    potentialYieldKgHa: 1200,
    price: { perQuintalInr: 8780, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 10000,
    byproductPerAcreInr: 1000,
    phRange: [6.0, 8.0],
    salinityToleranceEc: 1.0,
    nitrogenFixing: true,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Yellow mosaic (whitefly-borne)", "disease", "hot_dry", ["initial", "development"], "Use a YMV-resistant variety, yellow sticky traps, and rogue out infected plants."),
    ],
  },
  {
    id: "urad",
    name: "Black gram",
    localName: "Urad",
    category: "pulse",
    sowingWindows: [w("kharif", 6, 15, 7, 31), w("zaid", 3, 1, 4, 15)],
    durationDays: 80,
    stageFractions: [0.18, 0.27, 0.36, 0.19],
    stageLabels: PULSE_STAGES,
    stageNotes: PULSE_NOTES,
    temperature: { base: 12, optLow: 26, optHigh: 34, max: 42 },
    heatStressC: 40,
    coldStressC: 12,
    kc: { ini: 0.4, mid: 1.05, end: 0.35 },
    rootDepthM: 0.7,
    depletionFraction: 0.45,
    ky: 1.0,
    maxHeightCm: 50,
    harvestIndex: 0.3,
    potentialYieldKgHa: 1200,
    price: { perQuintalInr: 8200, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 10000,
    byproductPerAcreInr: 1000,
    phRange: [6.0, 8.0],
    salinityToleranceEc: 1.0,
    nitrogenFixing: true,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Yellow mosaic (whitefly-borne)", "disease", "hot_dry", ["initial", "development"], "Use a YMV-resistant variety and yellow sticky traps; remove infected plants."),
    ],
  },
  {
    id: "groundnut",
    name: "Groundnut",
    localName: "Moongphali",
    category: "oilseed",
    sowingWindows: [w("kharif", 6, 1, 7, 31), w("rabi", 12, 15, 1, 31)],
    durationDays: 115,
    stageFractions: [0.19, 0.27, 0.35, 0.19],
    stageLabels: ["Emergence", "Vegetative & pegging", "Pod development", "Pod maturity"],
    stageNotes: [
      "Seedlings emerge; a light, crust-free seedbed matters.",
      "Pegs enter the soil; gypsum at 200 kg/acre improves pod filling.",
      "Pods fill underground; soil must stay moist but not waterlogged.",
      "Inner shell darkens; lift the crop when 70% of pods are mature.",
    ],
    temperature: { base: 12, optLow: 25, optHigh: 32, max: 40 },
    heatStressC: 38,
    coldStressC: 12,
    kc: { ini: 0.4, mid: 1.15, end: 0.6 },
    rootDepthM: 0.8,
    depletionFraction: 0.5,
    ky: 0.7,
    maxHeightCm: 40,
    harvestIndex: 0.4,
    potentialYieldKgHa: 3000,
    price: { perQuintalInr: 7517, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 24000,
    byproductPerAcreInr: 3000,
    phRange: [5.5, 7.5],
    salinityToleranceEc: 1.6,
    nitrogenFixing: true,
    waterIntensity: "medium",
    residueBurningRisk: false,
    risks: [
      risk("Tikka leaf spot", "disease", "warm_humid", ["development", "mid"], "Spray carbendazim + mancozeb @ 2 g/L at first spots."),
    ],
  },
  {
    id: "soybean",
    name: "Soybean",
    localName: "Soyabean",
    category: "oilseed",
    sowingWindows: [w("kharif", 6, 15, 7, 20)],
    durationDays: 100,
    stageFractions: [0.15, 0.22, 0.44, 0.19],
    stageLabels: PULSE_STAGES,
    stageNotes: PULSE_NOTES,
    temperature: { base: 10, optLow: 24, optHigh: 32, max: 40 },
    heatStressC: 36,
    coldStressC: 10,
    kc: { ini: 0.4, mid: 1.15, end: 0.5 },
    rootDepthM: 1.0,
    depletionFraction: 0.5,
    ky: 0.85,
    maxHeightCm: 80,
    harvestIndex: 0.4,
    potentialYieldKgHa: 2800,
    price: { perQuintalInr: 5708, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 16000,
    byproductPerAcreInr: 1000,
    phRange: [6.0, 7.5],
    salinityToleranceEc: 2.5,
    nitrogenFixing: true,
    waterIntensity: "medium",
    residueBurningRisk: false,
    risks: [
      risk("Girdle beetle & semilooper", "pest", "warm_humid", ["development", "mid"], "Spray chlorantraniliprole 18.5 SC @ 0.3 ml/L when girdles or leaf damage exceed threshold."),
    ],
  },
  {
    id: "mustard",
    name: "Mustard",
    localName: "Sarson",
    category: "oilseed",
    sowingWindows: [w("rabi", 9, 25, 11, 15)],
    durationDays: 125,
    stageFractions: [0.17, 0.24, 0.38, 0.21],
    stageLabels: ["Germination & rosette", "Branching", "Flowering & siliqua filling", "Maturity"],
    stageNotes: OILSEED_NOTES,
    temperature: { base: 4, optLow: 14, optHigh: 24, max: 32 },
    heatStressC: 30,
    coldStressC: 1,
    kc: { ini: 0.35, mid: 1.0, end: 0.35 },
    rootDepthM: 1.2,
    depletionFraction: 0.6,
    ky: 0.9,
    maxHeightCm: 160,
    harvestIndex: 0.28,
    potentialYieldKgHa: 2000,
    price: { perQuintalInr: 6613, basis: RMS_2027 },
    priceVolatility: 0.15,
    costPerAcreInr: 13000,
    byproductPerAcreInr: 1000,
    phRange: [6.0, 8.5],
    salinityToleranceEc: 3.0,
    nitrogenFixing: false,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Mustard aphid", "pest", "cool_dry", ["mid"], "Spray only above 20 aphids per 10 cm of central shoot; imidacloprid 17.8 SL @ 0.25 ml/L, never during bee activity."),
      risk("Alternaria blight", "disease", "cool_humid", ["mid", "late"], "Spray mancozeb 75 WP @ 2.5 g/L at first dark concentric spots."),
    ],
  },
  {
    id: "sunflower",
    name: "Sunflower",
    localName: "Surajmukhi",
    category: "oilseed",
    sowingWindows: [w("kharif", 6, 15, 7, 31), w("rabi", 10, 15, 11, 30), w("zaid", 1, 15, 2, 28)],
    durationDays: 100,
    stageFractions: [0.19, 0.27, 0.35, 0.19],
    stageLabels: OILSEED_STAGES,
    stageNotes: OILSEED_NOTES,
    temperature: { base: 8, optLow: 20, optHigh: 30, max: 38 },
    heatStressC: 36,
    coldStressC: 4,
    kc: { ini: 0.35, mid: 1.0, end: 0.35 },
    rootDepthM: 1.2,
    depletionFraction: 0.45,
    ky: 0.95,
    maxHeightCm: 180,
    harvestIndex: 0.3,
    potentialYieldKgHa: 2200,
    price: { perQuintalInr: 8343, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 15000,
    byproductPerAcreInr: 500,
    phRange: [6.0, 8.0],
    salinityToleranceEc: 2.5,
    nitrogenFixing: false,
    waterIntensity: "medium",
    residueBurningRisk: false,
    risks: [
      risk("Head borer", "pest", "warm_flowering", ["mid"], "Use pheromone traps; spray NSKE 5% at bud stage."),
    ],
  },
  {
    id: "sesame",
    name: "Sesame",
    localName: "Til",
    category: "oilseed",
    sowingWindows: [w("kharif", 6, 15, 7, 31), w("zaid", 2, 1, 3, 15)],
    durationDays: 90,
    stageFractions: [0.18, 0.27, 0.36, 0.19],
    stageLabels: OILSEED_STAGES,
    stageNotes: OILSEED_NOTES,
    temperature: { base: 15, optLow: 27, optHigh: 34, max: 42 },
    heatStressC: 40,
    coldStressC: 15,
    kc: { ini: 0.35, mid: 1.1, end: 0.25 },
    rootDepthM: 1.2,
    depletionFraction: 0.6,
    ky: 0.9,
    maxHeightCm: 120,
    harvestIndex: 0.25,
    potentialYieldKgHa: 900,
    price: { perQuintalInr: 10346, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 9000,
    byproductPerAcreInr: 0,
    phRange: [5.5, 8.0],
    salinityToleranceEc: 1.5,
    nitrogenFixing: false,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Phyllody (leafhopper-borne)", "disease", "hot_dry", ["development", "mid"], "Rogue out affected plants and control leafhoppers early."),
    ],
  },
  {
    id: "cotton",
    name: "Cotton",
    localName: "Kapas",
    category: "cash",
    sowingWindows: [w("kharif", 4, 15, 6, 30)],
    durationDays: 170,
    stageFractions: [0.15, 0.26, 0.31, 0.28],
    stageLabels: ["Emergence", "Squaring", "Flowering & boll development", "Boll opening"],
    stageNotes: [
      "Seedlings emerge; gap-fill within 10 days.",
      "Squares (flower buds) form; watch for sucking pests.",
      "Bolls set and grow; the most water-sensitive period.",
      "Bolls burst open; pick in 3-4 rounds.",
    ],
    temperature: { base: 14, optLow: 25, optHigh: 33, max: 42 },
    heatStressC: 40,
    coldStressC: 12,
    kc: { ini: 0.35, mid: 1.15, end: 0.6 },
    rootDepthM: 1.4,
    depletionFraction: 0.65,
    ky: 0.85,
    maxHeightCm: 140,
    harvestIndex: 0.35,
    potentialYieldKgHa: 2500,
    price: { perQuintalInr: 8267, basis: KMS_2026 },
    priceVolatility: 0.15,
    costPerAcreInr: 32000,
    byproductPerAcreInr: 0,
    phRange: [6.0, 8.5],
    salinityToleranceEc: 4.0,
    nitrogenFixing: false,
    waterIntensity: "medium",
    residueBurningRisk: false,
    risks: [
      risk("Pink bollworm", "pest", "warm_flowering", ["mid"], "Install pheromone traps at 5 per acre; destroy rosette flowers; follow the ICAR spray schedule."),
      risk("Whitefly", "pest", "hot_dry", ["development", "mid"], "Use yellow sticky traps; avoid early synthetic pyrethroids that trigger resurgence."),
    ],
  },
  {
    id: "barley",
    name: "Barley",
    localName: "Jau",
    category: "cereal",
    sowingWindows: [w("rabi", 10, 20, 11, 30)],
    durationDays: 120,
    stageFractions: [0.125, 0.21, 0.42, 0.245],
    stageLabels: CEREAL_STAGES,
    stageNotes: CEREAL_NOTES,
    temperature: { base: 3, optLow: 14, optHigh: 22, max: 32 },
    heatStressC: 30,
    coldStressC: 0,
    kc: { ini: 0.3, mid: 1.15, end: 0.25 },
    rootDepthM: 1.2,
    depletionFraction: 0.55,
    ky: 1.0,
    maxHeightCm: 90,
    harvestIndex: 0.45,
    potentialYieldKgHa: 4000,
    price: { perQuintalInr: 2286, basis: RMS_2027 },
    priceVolatility: 0.15,
    costPerAcreInr: 11500,
    byproductPerAcreInr: 5000,
    phRange: [6.0, 8.8],
    salinityToleranceEc: 6.0,
    nitrogenFixing: false,
    waterIntensity: "low",
    residueBurningRisk: false,
    risks: [
      risk("Stripe rust", "disease", "cool_humid", ["development", "mid"], "Spray propiconazole 25 EC @ 1 ml/L at first stripes."),
    ],
  },
  {
    id: "potato",
    name: "Potato",
    localName: "Aloo",
    category: "vegetable",
    sowingWindows: [w("rabi", 10, 1, 11, 30)],
    durationDays: 105,
    stageFractions: [0.19, 0.23, 0.35, 0.23],
    stageLabels: ["Sprouting & emergence", "Stolon formation", "Tuber bulking", "Maturity & haulm cutting"],
    stageNotes: VEG_NOTES,
    temperature: { base: 5, optLow: 14, optHigh: 22, max: 30 },
    heatStressC: 30,
    coldStressC: 1,
    kc: { ini: 0.5, mid: 1.15, end: 0.75 },
    rootDepthM: 0.5,
    depletionFraction: 0.35,
    ky: 1.1,
    maxHeightCm: 60,
    harvestIndex: 0.75,
    potentialYieldKgHa: 30000,
    price: { perQuintalInr: 1300, basis: MANDI },
    priceVolatility: 0.4,
    costPerAcreInr: 65000,
    byproductPerAcreInr: 0,
    phRange: [5.0, 7.5],
    salinityToleranceEc: 1.2,
    nitrogenFixing: false,
    waterIntensity: "high",
    residueBurningRisk: false,
    risks: [
      risk("Late blight", "disease", "cool_humid", ["development", "mid"], "Spray mancozeb 75 WP @ 2.5 g/L prophylactically when cool, foggy weather sets in."),
    ],
  },
  {
    id: "onion",
    name: "Onion",
    localName: "Pyaz",
    category: "vegetable",
    sowingWindows: [w("rabi", 11, 1, 12, 31), w("kharif", 6, 1, 7, 31)],
    durationDays: 130,
    stageFractions: [0.1, 0.17, 0.47, 0.26],
    stageLabels: ["Transplant establishment", "Leaf growth", "Bulb development", "Bulb maturity"],
    stageNotes: VEG_NOTES,
    temperature: { base: 6, optLow: 15, optHigh: 25, max: 35 },
    heatStressC: 35,
    coldStressC: 2,
    kc: { ini: 0.7, mid: 1.05, end: 0.75 },
    rootDepthM: 0.4,
    depletionFraction: 0.3,
    ky: 1.1,
    maxHeightCm: 50,
    harvestIndex: 0.7,
    potentialYieldKgHa: 30000,
    price: { perQuintalInr: 1800, basis: MANDI },
    priceVolatility: 0.4,
    costPerAcreInr: 55000,
    byproductPerAcreInr: 0,
    phRange: [6.0, 7.5],
    salinityToleranceEc: 1.2,
    nitrogenFixing: false,
    waterIntensity: "high",
    residueBurningRisk: false,
    risks: [
      risk("Purple blotch", "disease", "warm_humid", ["mid"], "Spray mancozeb 75 WP @ 2.5 g/L with a sticker at first lesions."),
      risk("Thrips", "pest", "hot_dry", ["development", "mid"], "Use blue sticky traps; spray fipronil 5 SC @ 1.5 ml/L above threshold."),
    ],
  },
  {
    id: "tomato",
    name: "Tomato",
    localName: "Tamatar",
    category: "vegetable",
    sowingWindows: [w("kharif", 6, 1, 7, 31), w("rabi", 10, 1, 11, 30), w("zaid", 1, 1, 2, 28)],
    durationDays: 130,
    stageFractions: [0.22, 0.3, 0.3, 0.18],
    stageLabels: ["Transplant establishment", "Vegetative growth", "Flowering & fruit set", "Harvest period"],
    stageNotes: VEG_NOTES,
    temperature: { base: 10, optLow: 20, optHigh: 28, max: 35 },
    heatStressC: 33,
    coldStressC: 8,
    kc: { ini: 0.6, mid: 1.15, end: 0.8 },
    rootDepthM: 1.0,
    depletionFraction: 0.4,
    ky: 1.05,
    maxHeightCm: 100,
    harvestIndex: 0.6,
    potentialYieldKgHa: 35000,
    price: { perQuintalInr: 1500, basis: MANDI },
    priceVolatility: 0.4,
    costPerAcreInr: 70000,
    byproductPerAcreInr: 0,
    phRange: [6.0, 7.5],
    salinityToleranceEc: 1.7,
    nitrogenFixing: false,
    waterIntensity: "high",
    residueBurningRisk: false,
    risks: [
      risk("Leaf curl virus (whitefly-borne)", "disease", "hot_dry", ["initial", "development"], "Raise nursery under insect net; use yellow sticky traps and resistant hybrids."),
      risk("Early blight", "disease", "warm_humid", ["mid", "late"], "Spray mancozeb 75 WP @ 2.5 g/L; remove lower infected leaves."),
    ],
  },
];

const BY_ID = new Map(CROPS.map((c) => [c.id, c]));

export function getCrop(id: string): CropModel | undefined {
  return BY_ID.get(id);
}

export function requireCrop(id: string): CropModel {
  const crop = BY_ID.get(id);
  if (!crop) throw new Error(`Unknown crop id: ${id}`);
  return crop;
}

export const CROP_IDS = CROPS.map((c) => c.id);
